// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bcgxqfssjheltpfhlocj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJjZ3hxZnNzamhlbHRwZmhsb2NqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyNDY2NzAsImV4cCI6MjA2NTgyMjY3MH0.MKOFCjmfj6m2wPmaLhO-PtpzPW5iO6Oj_x7f-PWfaOs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);